//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCK_WPFclient.LCK_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flavor", Namespace="http://schemas.datacontract.org/2004/07/LCK_DBcommunication.LCK_DataObjects")]
    [System.SerializableAttribute()]
    public partial class Flavor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Batch", Namespace="http://schemas.datacontract.org/2004/07/LCK_DBcommunication.LCK_DataObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LCK_WPFclient.LCK_ServiceReference.SO_Batch))]
    public partial class Batch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LCK_WPFclient.LCK_ServiceReference.Flavor FlavorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LCK_WPFclient.LCK_ServiceReference.StoreInfo StoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day_Number {
            get {
                return this.Day_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Day_NumberField, value) != true)) {
                    this.Day_NumberField = value;
                    this.RaisePropertyChanged("Day_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LCK_WPFclient.LCK_ServiceReference.Flavor Flavor {
            get {
                return this.FlavorField;
            }
            set {
                if ((object.ReferenceEquals(this.FlavorField, value) != true)) {
                    this.FlavorField = value;
                    this.RaisePropertyChanged("Flavor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Requested {
            get {
                return this.RequestedField;
            }
            set {
                if ((this.RequestedField.Equals(value) != true)) {
                    this.RequestedField = value;
                    this.RaisePropertyChanged("Requested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LCK_WPFclient.LCK_ServiceReference.StoreInfo Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreInfo", Namespace="http://schemas.datacontract.org/2004/07/LCK_DBcommunication.LCK_DataObjects")]
    [System.SerializableAttribute()]
    public partial class StoreInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SO_Batch", Namespace="http://schemas.datacontract.org/2004/07/LCK_DBcommunication.LCK_DataObjects")]
    [System.SerializableAttribute()]
    public partial class SO_Batch : LCK_WPFclient.LCK_ServiceReference.Batch {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Is_MiniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SO_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Special_InstructionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Is_Mini {
            get {
                return this.Is_MiniField;
            }
            set {
                if ((this.Is_MiniField.Equals(value) != true)) {
                    this.Is_MiniField = value;
                    this.RaisePropertyChanged("Is_Mini");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SO_ID {
            get {
                return this.SO_IDField;
            }
            set {
                if ((this.SO_IDField.Equals(value) != true)) {
                    this.SO_IDField = value;
                    this.RaisePropertyChanged("SO_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Special_Instructions {
            get {
                return this.Special_InstructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.Special_InstructionsField, value) != true)) {
                    this.Special_InstructionsField = value;
                    this.RaisePropertyChanged("Special_Instructions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialOrder", Namespace="http://schemas.datacontract.org/2004/07/LCK_DBcommunication.LCK_DataObjects")]
    [System.SerializableAttribute()]
    public partial class SpecialOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LCK_WPFclient.LCK_ServiceReference.SO_Batch[] BatchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Customer_AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Customer_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Customer_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeliverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScanLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialInstructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LCK_WPFclient.LCK_ServiceReference.StoreInfo StoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LCK_WPFclient.LCK_ServiceReference.SO_Batch[] Batches {
            get {
                return this.BatchesField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchesField, value) != true)) {
                    this.BatchesField = value;
                    this.RaisePropertyChanged("Batches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_Address {
            get {
                return this.Customer_AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.Customer_AddressField, value) != true)) {
                    this.Customer_AddressField = value;
                    this.RaisePropertyChanged("Customer_Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_Name {
            get {
                return this.Customer_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Customer_NameField, value) != true)) {
                    this.Customer_NameField = value;
                    this.RaisePropertyChanged("Customer_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_Phone {
            get {
                return this.Customer_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Customer_PhoneField, value) != true)) {
                    this.Customer_PhoneField = value;
                    this.RaisePropertyChanged("Customer_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day_Number {
            get {
                return this.Day_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Day_NumberField, value) != true)) {
                    this.Day_NumberField = value;
                    this.RaisePropertyChanged("Day_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deliver {
            get {
                return this.DeliverField;
            }
            set {
                if ((this.DeliverField.Equals(value) != true)) {
                    this.DeliverField = value;
                    this.RaisePropertyChanged("Deliver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DueTime {
            get {
                return this.DueTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DueTimeField, value) != true)) {
                    this.DueTimeField = value;
                    this.RaisePropertyChanged("DueTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScanLink {
            get {
                return this.ScanLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanLinkField, value) != true)) {
                    this.ScanLinkField = value;
                    this.RaisePropertyChanged("ScanLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialInstructions {
            get {
                return this.SpecialInstructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialInstructionsField, value) != true)) {
                    this.SpecialInstructionsField = value;
                    this.RaisePropertyChanged("SpecialInstructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LCK_WPFclient.LCK_ServiceReference.StoreInfo Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DayPreview", Namespace="http://schemas.datacontract.org/2004/07/LCK_DBcommunication.LCK_DataObjects")]
    [System.SerializableAttribute()]
    public partial class DayPreview : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DailyFlavorCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SO_QtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DailyFlavorCount {
            get {
                return this.DailyFlavorCountField;
            }
            set {
                if ((this.DailyFlavorCountField.Equals(value) != true)) {
                    this.DailyFlavorCountField = value;
                    this.RaisePropertyChanged("DailyFlavorCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SO_Qty {
            get {
                return this.SO_QtyField;
            }
            set {
                if ((this.SO_QtyField.Equals(value) != true)) {
                    this.SO_QtyField = value;
                    this.RaisePropertyChanged("SO_Qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DayInfo", Namespace="http://schemas.datacontract.org/2004/07/LCK_DBcommunication.LCK_DataObjects")]
    [System.SerializableAttribute()]
    public partial class DayInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DayNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LCK_WPFclient.LCK_ServiceReference.Flavor[] FlavorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LCK_WPFclient.LCK_ServiceReference.SpecialOrder[] OrdersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DayNumber {
            get {
                return this.DayNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DayNumberField, value) != true)) {
                    this.DayNumberField = value;
                    this.RaisePropertyChanged("DayNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LCK_WPFclient.LCK_ServiceReference.Flavor[] Flavors {
            get {
                return this.FlavorsField;
            }
            set {
                if ((object.ReferenceEquals(this.FlavorsField, value) != true)) {
                    this.FlavorsField = value;
                    this.RaisePropertyChanged("Flavors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LCK_WPFclient.LCK_ServiceReference.SpecialOrder[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LCK_ServiceReference.ILCK_Service")]
    public interface ILCK_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetAllFlavors", ReplyAction="http://tempuri.org/ILCK_Service/GetAllFlavorsResponse")]
        LCK_WPFclient.LCK_ServiceReference.Flavor[] GetAllFlavors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetAllFlavors", ReplyAction="http://tempuri.org/ILCK_Service/GetAllFlavorsResponse")]
        System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.Flavor[]> GetAllFlavorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetBatches", ReplyAction="http://tempuri.org/ILCK_Service/GetBatchesResponse")]
        LCK_WPFclient.LCK_ServiceReference.Batch[] GetBatches(int StoreID, string DayNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetBatches", ReplyAction="http://tempuri.org/ILCK_Service/GetBatchesResponse")]
        System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.Batch[]> GetBatchesAsync(int StoreID, string DayNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetDailyFlavors", ReplyAction="http://tempuri.org/ILCK_Service/GetDailyFlavorsResponse")]
        LCK_WPFclient.LCK_ServiceReference.Batch[] GetDailyFlavors(int StoreID, string DayNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetDailyFlavors", ReplyAction="http://tempuri.org/ILCK_Service/GetDailyFlavorsResponse")]
        System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.Batch[]> GetDailyFlavorsAsync(int StoreID, string DayNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetStoreInfoByID", ReplyAction="http://tempuri.org/ILCK_Service/GetStoreInfoByIDResponse")]
        LCK_WPFclient.LCK_ServiceReference.StoreInfo GetStoreInfoByID(int StoreID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetStoreInfoByID", ReplyAction="http://tempuri.org/ILCK_Service/GetStoreInfoByIDResponse")]
        System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.StoreInfo> GetStoreInfoByIDAsync(int StoreID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetStoreInfo", ReplyAction="http://tempuri.org/ILCK_Service/GetStoreInfoResponse")]
        LCK_WPFclient.LCK_ServiceReference.StoreInfo GetStoreInfo(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetStoreInfo", ReplyAction="http://tempuri.org/ILCK_Service/GetStoreInfoResponse")]
        System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.StoreInfo> GetStoreInfoAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetSpecialOrder", ReplyAction="http://tempuri.org/ILCK_Service/GetSpecialOrderResponse")]
        LCK_WPFclient.LCK_ServiceReference.SpecialOrder GetSpecialOrder(int SO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetSpecialOrder", ReplyAction="http://tempuri.org/ILCK_Service/GetSpecialOrderResponse")]
        System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.SpecialOrder> GetSpecialOrderAsync(int SO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetSpecialOrders", ReplyAction="http://tempuri.org/ILCK_Service/GetSpecialOrdersResponse")]
        LCK_WPFclient.LCK_ServiceReference.SpecialOrder[] GetSpecialOrders(int StoreID, string DayNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetSpecialOrders", ReplyAction="http://tempuri.org/ILCK_Service/GetSpecialOrdersResponse")]
        System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.SpecialOrder[]> GetSpecialOrdersAsync(int StoreID, string DayNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetPreviews", ReplyAction="http://tempuri.org/ILCK_Service/GetPreviewsResponse")]
        LCK_WPFclient.LCK_ServiceReference.DayPreview[] GetPreviews(int StoreID, string startDay_number, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetPreviews", ReplyAction="http://tempuri.org/ILCK_Service/GetPreviewsResponse")]
        System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.DayPreview[]> GetPreviewsAsync(int StoreID, string startDay_number, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetDayInfo", ReplyAction="http://tempuri.org/ILCK_Service/GetDayInfoResponse")]
        LCK_WPFclient.LCK_ServiceReference.DayInfo GetDayInfo(int StoreID, string DayNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetDayInfo", ReplyAction="http://tempuri.org/ILCK_Service/GetDayInfoResponse")]
        System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.DayInfo> GetDayInfoAsync(int StoreID, string DayNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetAllStoresInfo", ReplyAction="http://tempuri.org/ILCK_Service/GetAllStoresInfoResponse")]
        LCK_WPFclient.LCK_ServiceReference.StoreInfo[] GetAllStoresInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/GetAllStoresInfo", ReplyAction="http://tempuri.org/ILCK_Service/GetAllStoresInfoResponse")]
        System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.StoreInfo[]> GetAllStoresInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/AddFlavor", ReplyAction="http://tempuri.org/ILCK_Service/AddFlavorResponse")]
        bool AddFlavor(LCK_WPFclient.LCK_ServiceReference.Flavor flav);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/AddFlavor", ReplyAction="http://tempuri.org/ILCK_Service/AddFlavorResponse")]
        System.Threading.Tasks.Task<bool> AddFlavorAsync(LCK_WPFclient.LCK_ServiceReference.Flavor flav);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/AddSpecialOrder", ReplyAction="http://tempuri.org/ILCK_Service/AddSpecialOrderResponse")]
        bool AddSpecialOrder(LCK_WPFclient.LCK_ServiceReference.SpecialOrder SO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/AddSpecialOrder", ReplyAction="http://tempuri.org/ILCK_Service/AddSpecialOrderResponse")]
        System.Threading.Tasks.Task<bool> AddSpecialOrderAsync(LCK_WPFclient.LCK_ServiceReference.SpecialOrder SO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/AddSpecialOrderBatch", ReplyAction="http://tempuri.org/ILCK_Service/AddSpecialOrderBatchResponse")]
        bool AddSpecialOrderBatch(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SO_Batch batch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/AddSpecialOrderBatch", ReplyAction="http://tempuri.org/ILCK_Service/AddSpecialOrderBatchResponse")]
        System.Threading.Tasks.Task<bool> AddSpecialOrderBatchAsync(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SO_Batch batch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/AddStore", ReplyAction="http://tempuri.org/ILCK_Service/AddStoreResponse")]
        bool AddStore(LCK_WPFclient.LCK_ServiceReference.StoreInfo Store);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/AddStore", ReplyAction="http://tempuri.org/ILCK_Service/AddStoreResponse")]
        System.Threading.Tasks.Task<bool> AddStoreAsync(LCK_WPFclient.LCK_ServiceReference.StoreInfo Store);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/UpdateSpecialOrder", ReplyAction="http://tempuri.org/ILCK_Service/UpdateSpecialOrderResponse")]
        bool UpdateSpecialOrder(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SpecialOrder updatedSO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/UpdateSpecialOrder", ReplyAction="http://tempuri.org/ILCK_Service/UpdateSpecialOrderResponse")]
        System.Threading.Tasks.Task<bool> UpdateSpecialOrderAsync(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SpecialOrder updatedSO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/UpdateSpecialOrderBatch", ReplyAction="http://tempuri.org/ILCK_Service/UpdateSpecialOrderBatchResponse")]
        bool UpdateSpecialOrderBatch(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SO_Batch updatedBatch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/UpdateSpecialOrderBatch", ReplyAction="http://tempuri.org/ILCK_Service/UpdateSpecialOrderBatchResponse")]
        System.Threading.Tasks.Task<bool> UpdateSpecialOrderBatchAsync(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SO_Batch updatedBatch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/UpdateBatch", ReplyAction="http://tempuri.org/ILCK_Service/UpdateBatchResponse")]
        bool UpdateBatch(int Batch_ID, LCK_WPFclient.LCK_ServiceReference.Batch updatedBatch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/UpdateBatch", ReplyAction="http://tempuri.org/ILCK_Service/UpdateBatchResponse")]
        System.Threading.Tasks.Task<bool> UpdateBatchAsync(int Batch_ID, LCK_WPFclient.LCK_ServiceReference.Batch updatedBatch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/UpdateFlavor", ReplyAction="http://tempuri.org/ILCK_Service/UpdateFlavorResponse")]
        bool UpdateFlavor(int Flavor_ID, LCK_WPFclient.LCK_ServiceReference.Flavor updatedFlavor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/UpdateFlavor", ReplyAction="http://tempuri.org/ILCK_Service/UpdateFlavorResponse")]
        System.Threading.Tasks.Task<bool> UpdateFlavorAsync(int Flavor_ID, LCK_WPFclient.LCK_ServiceReference.Flavor updatedFlavor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/UpdateStore", ReplyAction="http://tempuri.org/ILCK_Service/UpdateStoreResponse")]
        bool UpdateStore(int Store_ID, LCK_WPFclient.LCK_ServiceReference.StoreInfo updatedStore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/UpdateStore", ReplyAction="http://tempuri.org/ILCK_Service/UpdateStoreResponse")]
        System.Threading.Tasks.Task<bool> UpdateStoreAsync(int Store_ID, LCK_WPFclient.LCK_ServiceReference.StoreInfo updatedStore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/DeleteSpecialOrder", ReplyAction="http://tempuri.org/ILCK_Service/DeleteSpecialOrderResponse")]
        bool DeleteSpecialOrder(int SO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/DeleteSpecialOrder", ReplyAction="http://tempuri.org/ILCK_Service/DeleteSpecialOrderResponse")]
        System.Threading.Tasks.Task<bool> DeleteSpecialOrderAsync(int SO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/DeleteSpecialOrderBatch", ReplyAction="http://tempuri.org/ILCK_Service/DeleteSpecialOrderBatchResponse")]
        bool DeleteSpecialOrderBatch(int Batch_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/DeleteSpecialOrderBatch", ReplyAction="http://tempuri.org/ILCK_Service/DeleteSpecialOrderBatchResponse")]
        System.Threading.Tasks.Task<bool> DeleteSpecialOrderBatchAsync(int Batch_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/DeleteBatch", ReplyAction="http://tempuri.org/ILCK_Service/DeleteBatchResponse")]
        bool DeleteBatch(int Batch_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/DeleteBatch", ReplyAction="http://tempuri.org/ILCK_Service/DeleteBatchResponse")]
        System.Threading.Tasks.Task<bool> DeleteBatchAsync(int Batch_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/DeleteFlavor", ReplyAction="http://tempuri.org/ILCK_Service/DeleteFlavorResponse")]
        bool DeleteFlavor(int Flavor_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/DeleteFlavor", ReplyAction="http://tempuri.org/ILCK_Service/DeleteFlavorResponse")]
        System.Threading.Tasks.Task<bool> DeleteFlavorAsync(int Flavor_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/DeleteStore", ReplyAction="http://tempuri.org/ILCK_Service/DeleteStoreResponse")]
        bool DeleteStore(int Store_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCK_Service/DeleteStore", ReplyAction="http://tempuri.org/ILCK_Service/DeleteStoreResponse")]
        System.Threading.Tasks.Task<bool> DeleteStoreAsync(int Store_ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILCK_ServiceChannel : LCK_WPFclient.LCK_ServiceReference.ILCK_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LCK_ServiceClient : System.ServiceModel.ClientBase<LCK_WPFclient.LCK_ServiceReference.ILCK_Service>, LCK_WPFclient.LCK_ServiceReference.ILCK_Service {
        
        public LCK_ServiceClient() {
        }
        
        public LCK_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LCK_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LCK_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LCK_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LCK_WPFclient.LCK_ServiceReference.Flavor[] GetAllFlavors() {
            return base.Channel.GetAllFlavors();
        }
        
        public System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.Flavor[]> GetAllFlavorsAsync() {
            return base.Channel.GetAllFlavorsAsync();
        }
        
        public LCK_WPFclient.LCK_ServiceReference.Batch[] GetBatches(int StoreID, string DayNumber) {
            return base.Channel.GetBatches(StoreID, DayNumber);
        }
        
        public System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.Batch[]> GetBatchesAsync(int StoreID, string DayNumber) {
            return base.Channel.GetBatchesAsync(StoreID, DayNumber);
        }
        
        public LCK_WPFclient.LCK_ServiceReference.Batch[] GetDailyFlavors(int StoreID, string DayNumber) {
            return base.Channel.GetDailyFlavors(StoreID, DayNumber);
        }
        
        public System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.Batch[]> GetDailyFlavorsAsync(int StoreID, string DayNumber) {
            return base.Channel.GetDailyFlavorsAsync(StoreID, DayNumber);
        }
        
        public LCK_WPFclient.LCK_ServiceReference.StoreInfo GetStoreInfoByID(int StoreID) {
            return base.Channel.GetStoreInfoByID(StoreID);
        }
        
        public System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.StoreInfo> GetStoreInfoByIDAsync(int StoreID) {
            return base.Channel.GetStoreInfoByIDAsync(StoreID);
        }
        
        public LCK_WPFclient.LCK_ServiceReference.StoreInfo GetStoreInfo(string Name) {
            return base.Channel.GetStoreInfo(Name);
        }
        
        public System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.StoreInfo> GetStoreInfoAsync(string Name) {
            return base.Channel.GetStoreInfoAsync(Name);
        }
        
        public LCK_WPFclient.LCK_ServiceReference.SpecialOrder GetSpecialOrder(int SO_ID) {
            return base.Channel.GetSpecialOrder(SO_ID);
        }
        
        public System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.SpecialOrder> GetSpecialOrderAsync(int SO_ID) {
            return base.Channel.GetSpecialOrderAsync(SO_ID);
        }
        
        public LCK_WPFclient.LCK_ServiceReference.SpecialOrder[] GetSpecialOrders(int StoreID, string DayNumber) {
            return base.Channel.GetSpecialOrders(StoreID, DayNumber);
        }
        
        public System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.SpecialOrder[]> GetSpecialOrdersAsync(int StoreID, string DayNumber) {
            return base.Channel.GetSpecialOrdersAsync(StoreID, DayNumber);
        }
        
        public LCK_WPFclient.LCK_ServiceReference.DayPreview[] GetPreviews(int StoreID, string startDay_number, int count) {
            return base.Channel.GetPreviews(StoreID, startDay_number, count);
        }
        
        public System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.DayPreview[]> GetPreviewsAsync(int StoreID, string startDay_number, int count) {
            return base.Channel.GetPreviewsAsync(StoreID, startDay_number, count);
        }
        
        public LCK_WPFclient.LCK_ServiceReference.DayInfo GetDayInfo(int StoreID, string DayNumber) {
            return base.Channel.GetDayInfo(StoreID, DayNumber);
        }
        
        public System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.DayInfo> GetDayInfoAsync(int StoreID, string DayNumber) {
            return base.Channel.GetDayInfoAsync(StoreID, DayNumber);
        }
        
        public LCK_WPFclient.LCK_ServiceReference.StoreInfo[] GetAllStoresInfo() {
            return base.Channel.GetAllStoresInfo();
        }
        
        public System.Threading.Tasks.Task<LCK_WPFclient.LCK_ServiceReference.StoreInfo[]> GetAllStoresInfoAsync() {
            return base.Channel.GetAllStoresInfoAsync();
        }
        
        public bool AddFlavor(LCK_WPFclient.LCK_ServiceReference.Flavor flav) {
            return base.Channel.AddFlavor(flav);
        }
        
        public System.Threading.Tasks.Task<bool> AddFlavorAsync(LCK_WPFclient.LCK_ServiceReference.Flavor flav) {
            return base.Channel.AddFlavorAsync(flav);
        }
        
        public bool AddSpecialOrder(LCK_WPFclient.LCK_ServiceReference.SpecialOrder SO) {
            return base.Channel.AddSpecialOrder(SO);
        }
        
        public System.Threading.Tasks.Task<bool> AddSpecialOrderAsync(LCK_WPFclient.LCK_ServiceReference.SpecialOrder SO) {
            return base.Channel.AddSpecialOrderAsync(SO);
        }
        
        public bool AddSpecialOrderBatch(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SO_Batch batch) {
            return base.Channel.AddSpecialOrderBatch(SO_ID, batch);
        }
        
        public System.Threading.Tasks.Task<bool> AddSpecialOrderBatchAsync(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SO_Batch batch) {
            return base.Channel.AddSpecialOrderBatchAsync(SO_ID, batch);
        }
        
        public bool AddStore(LCK_WPFclient.LCK_ServiceReference.StoreInfo Store) {
            return base.Channel.AddStore(Store);
        }
        
        public System.Threading.Tasks.Task<bool> AddStoreAsync(LCK_WPFclient.LCK_ServiceReference.StoreInfo Store) {
            return base.Channel.AddStoreAsync(Store);
        }
        
        public bool UpdateSpecialOrder(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SpecialOrder updatedSO) {
            return base.Channel.UpdateSpecialOrder(SO_ID, updatedSO);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSpecialOrderAsync(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SpecialOrder updatedSO) {
            return base.Channel.UpdateSpecialOrderAsync(SO_ID, updatedSO);
        }
        
        public bool UpdateSpecialOrderBatch(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SO_Batch updatedBatch) {
            return base.Channel.UpdateSpecialOrderBatch(SO_ID, updatedBatch);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSpecialOrderBatchAsync(int SO_ID, LCK_WPFclient.LCK_ServiceReference.SO_Batch updatedBatch) {
            return base.Channel.UpdateSpecialOrderBatchAsync(SO_ID, updatedBatch);
        }
        
        public bool UpdateBatch(int Batch_ID, LCK_WPFclient.LCK_ServiceReference.Batch updatedBatch) {
            return base.Channel.UpdateBatch(Batch_ID, updatedBatch);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBatchAsync(int Batch_ID, LCK_WPFclient.LCK_ServiceReference.Batch updatedBatch) {
            return base.Channel.UpdateBatchAsync(Batch_ID, updatedBatch);
        }
        
        public bool UpdateFlavor(int Flavor_ID, LCK_WPFclient.LCK_ServiceReference.Flavor updatedFlavor) {
            return base.Channel.UpdateFlavor(Flavor_ID, updatedFlavor);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateFlavorAsync(int Flavor_ID, LCK_WPFclient.LCK_ServiceReference.Flavor updatedFlavor) {
            return base.Channel.UpdateFlavorAsync(Flavor_ID, updatedFlavor);
        }
        
        public bool UpdateStore(int Store_ID, LCK_WPFclient.LCK_ServiceReference.StoreInfo updatedStore) {
            return base.Channel.UpdateStore(Store_ID, updatedStore);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStoreAsync(int Store_ID, LCK_WPFclient.LCK_ServiceReference.StoreInfo updatedStore) {
            return base.Channel.UpdateStoreAsync(Store_ID, updatedStore);
        }
        
        public bool DeleteSpecialOrder(int SO_ID) {
            return base.Channel.DeleteSpecialOrder(SO_ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSpecialOrderAsync(int SO_ID) {
            return base.Channel.DeleteSpecialOrderAsync(SO_ID);
        }
        
        public bool DeleteSpecialOrderBatch(int Batch_ID) {
            return base.Channel.DeleteSpecialOrderBatch(Batch_ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSpecialOrderBatchAsync(int Batch_ID) {
            return base.Channel.DeleteSpecialOrderBatchAsync(Batch_ID);
        }
        
        public bool DeleteBatch(int Batch_ID) {
            return base.Channel.DeleteBatch(Batch_ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBatchAsync(int Batch_ID) {
            return base.Channel.DeleteBatchAsync(Batch_ID);
        }
        
        public bool DeleteFlavor(int Flavor_ID) {
            return base.Channel.DeleteFlavor(Flavor_ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFlavorAsync(int Flavor_ID) {
            return base.Channel.DeleteFlavorAsync(Flavor_ID);
        }
        
        public bool DeleteStore(int Store_ID) {
            return base.Channel.DeleteStore(Store_ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStoreAsync(int Store_ID) {
            return base.Channel.DeleteStoreAsync(Store_ID);
        }
    }
}
